### ISSUE TITLE
Load image randomly (?) throws WebException: "The request was aborted: Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by schdck** [ArthurHub/HTML-Renderer#149]
Sometimes when loading an image from internet, a WebException would be thrown with the following message:

> The request was aborted: Could not create SSL/TLS secure channel

I currently don't have another computer to test on, but on my machine the following snippet throws de exception 100% of time (maybe because the website does not support TLS 1.0 and/or 1.1?):

    <htmlRenderer:HtmlPanel Text="&lt;html&gt;&lt;body&gt;&lt;img src=&quot;https://eleaut.com.br/imagens_assinatura/logo.png&quot; /&gt;&lt;/body&gt;&lt;/html&gt; " />

Apparently the error can be solved quite simply by adding the following line (taken from [here](https://stackoverflow.com/a/48930280/5686352)):

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Or, since we are on .NET 3.0, this one:

    ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;

I'll do a PR as soon as I can :)

**Comment by amoraller** [comment]
Fix crash my app if .Net 4.5 not installed.
For example, win xp or 

`System.NotSupportedException The requested security protocol is not supported. Void set_SecurityProtocol(System.Net.SecurityProtocolType)    at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   at TheArtOfDev.HtmlRenderer.Core.Handlers.ImageDownloader..ctor() in C:\BuildAgent\work\7617a0d19e6dbcb6\HTML-Renderer\Source\HtmlRenderer\Core\Handlers\ImageDownloader.cs:line 53
   at TheArtOfDev.HtmlRenderer.Core.HtmlContainerInt.SetHtml(String htmlSource, CssData baseCssData) in C:\BuildAgent\work\7617a0d19e6dbcb6\HTML-Renderer\Source\HtmlRenderer\Core\HtmlContainerInt.cs:line 520
   at TheArtOfDev.HtmlRenderer.WPF.HtmlControl.OnDependencyProperty_valueChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e) in C:\BuildAgent\work\7617a0d19e6dbcb6\HTML-Renderer\Source\HtmlRenderer.WPF\HtmlControl.cs:line 495`
